utan/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from investasi.views import (
    HomePageView,
    DetailProject,
    UserView,
    Invoice,
    Transaksi
)
from userapp.views import (
    LoginUser,
    DaftarUser,
    Logout
)

urlpatterns = patterns('',
    url(r'^$', HomePageView.as_view(), name='homepageview'),
    url(r'^login/$', LoginUser.as_view(), name='login'),
    url(r'^logout/$', Logout , name='logout'),
    url(r'^daftar/$', DaftarUser.as_view(), name='daftaruser'),
    url(r'^profile/$', UserView.as_view(), name='userprofile'),
    url(r'^invoice/$', Invoice.as_view(), name='Invoice'),
                       
    url(r'^detailproject/(?P<slug>[\w\d\-\.]+)$', DetailProject.as_view(), name='detailproject'),
    url(r'^transaksi/(?P<slug>[\w\d\-\.]+)$', Transaksi.as_view(), name='transaksi'),
                       
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                 {'document_root': settings.MEDIA_ROOT}),

)

admin.autodiscover()
urlpatterns += patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
)

investasi/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from userapp.models import UserProfile
from django.template import defaultfilters
from decimal import Decimal
import uuid
import random
import string
import unicodedata

from io import BytesIO

from xhtml2pdf import pisa

from django.http import HttpResponse
from django.template import Context
from django.template.loader import render_to_string, get_template
from django.core.mail import EmailMessage

class GetOrNoneManager(models.Manager):
    """Adds get_or_none method to objects
    """
    def get_or_none(self, **kwargs):
        try:
            return self.get(**kwargs)
        except self.model.DoesNotExist:
            return None
        
        
    

def key_generator(limit=10):
    uuid_set = str(uuid.uuid4().fields[-1])[:5]
    d = [random.choice(string.letters + string.digits + uuid_set) for x in xrange(limit)]
    key = "".join(d)
    return key




class Project(models.Model):
    name = models.CharField(max_length=255, unique=True)
    uniquecode = models.CharField(max_length=300, blank=True, null=True, unique=True)
    slug = models.CharField(max_length=300, blank=True, null=True, unique=True)
    price = models.DecimalField(blank=True, null=True, max_digits=15, decimal_places=0)
    lama_investasi = models.CharField(max_length=255, blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    finding_needs = models.DecimalField(blank=True, null=True, max_digits=15, decimal_places=0)
    Profit_Prediction = models.DecimalField(blank=True, null=True, max_digits=15, decimal_places=0)
    risk_sts = (('1', 'Rendah'), ('2', 'Sedang'), ('3', 'Tinggi'))
    risk_status = models.CharField(max_length=1, blank=True, null=True, choices=risk_sts)
    lat = models.CharField(max_length=100, blank=True, null=True)
    lang = models.CharField("long", max_length=100, blank=True, null=True)
    lokasi  = models.TextField(blank=True, null=True, verbose_name='lokasi', help_text="Deskripsi lokasi") 
    description  = models.TextField(blank=True, null=True, verbose_name='deskripsi', help_text="Deskripsi produk organik blablabla") 
    photo = models.ImageField('Photo', upload_to="photo_proj", blank=True, null=True)
    active = models.BooleanField(default=True)
    sts_project = (('1', 'Menunggu Pendanaan Terpenuhi'), ('2', 'Proses Tanam'), ('3', 'Panen'))
    project_status = models.CharField(max_length=1, blank=True, null=True, choices=sts_project, default='1')
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    objects = GetOrNoneManager()
    
    def get_pendanaan(self):
        data = []
        for i in self.member_set.all():
            data.append(i.aoi)
        if len (data):
            print data
        return sum(data)  
         
    def get_persen(self):
        kebutuhan = Decimal(self.finding_needs)
        terkumpul = Decimal(self.get_pendanaan())
        persen = terkumpul*100/kebutuhan
        persen = round(persen)
        return format(persen, '.15g')  
            
    
    def save(self, *args, **kwargs):
        self.slug = defaultfilters.slugify(self.name)
        self.uniquecode = defaultfilters.slugify(key_generator(5))
        super(Project, self).save(*args, **kwargs)
    
    def __unicode__(self):
        return self.name
    
#class Investing (Data Table Investing) 

from easy_pdf.rendering import render_to_pdf
from xhtml2pdf import pisa 
import cStringIO as StringIO
import cgi

def render_to_pdf(template_src, context_dict):
    template = get_template(template_src)
    context = Context(context_dict)
    html  = template.render(context)
    result = StringIO.StringIO()
    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return result
    return None

def sendemail(subject, to, data, html):
    try:
     message = get_template(html).render(Context(data))
     pdf = render_to_pdf(html, data)
     msg = EmailMessage(subject, message, to=to, from_email="admin@pipo.asia")
     msg.content_subtype = 'html'
     msg.attach('invoicex.pdf', pdf.getvalue() , 'application/pdf')
     return msg.send()
    except Exception,err:
        print err

class Member(models.Model):
    project = models.ForeignKey(Project, verbose_name='project',blank=True, null=True)
    user = models.ForeignKey(UserProfile, verbose_name='UserProfile', blank=True, null=True)
    uniquecode = models.CharField(max_length=300, blank=True, null=True, unique=True)
    aoi = models.DecimalField(blank=True, null=True, max_digits=18, decimal_places=0)
    profit = models.DecimalField(blank=True, null=True, max_digits=18, decimal_places=0)
    toi =models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)
    objects = GetOrNoneManager()
    
    def save(self, *args, **kwargs):
        if self.status:
            transaction = Transaction.objects.create(
                member=Member.objects.get(id = self.id),
                moneyin=self.aoi,
            )
            transaction.save()
            subject = "Pipo.asia: Invoice #%s Untuk Proyek %s" % (self.uniquecode, self.project.name)
            to = [self.user.email]
            html = "invoice.html"
            data = {
               'invoiceid': self.project.uniquecode,
               'pname': self.project.name,
               'paoi': self.aoi
            }
            sendemail(subject, to, data, html)

        super(Member, self).save(*args, **kwargs)
    
    def __unicode__(self):
        return unicode(self.uniquecode) or u''
     


#class untuk galery foto dari project
class Gallery(models.Model):
    project = models.ForeignKey(Project,blank=True, null=True)
    name = models.CharField(blank=True, null=True, max_length=200)
    slug = models.CharField(max_length=300, blank=True, null=True)
    photo = models.ImageField('Photo', upload_to="photo_proj", blank=True, null=True)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    
    def save(self, *args, **kwargs):
        self.name = self.photo.name
        self.slug = defaultfilters.slugify(self.name)
        super(Gallery, self).save(*args, **kwargs)

    def __str__(self):
        return "%s" % (self.name)

admin.site.register(Gallery)

class Transaction(models.Model):
    member = models.ForeignKey(Member, null=True)
    moneyout = models.DecimalField(max_digits=20, blank=True, null=True, decimal_places=0)
    moneyin = models.DecimalField(max_digits=20, blank=True, null=True, decimal_places=0)
    
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return unicode(self.id) or u''
    
admin.site.register(Transaction)

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>pipo </title>
        <link rel="stylesheet" href="/static/asset/ico/css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="/static/asset/bootstrap/css/bootstrap.css" type="text/css">
        <link rel="stylesheet" href="/static/asset/bootstrap_select/dist/css/bootstrap-select.min.css">
        <link rel="stylesheet" href="/static/asset/css/navbtm.css">
        <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
        <link href="/static/asset/icon/logo_circle.png" rel="icon">
        {% block css %}{% endblock %}
    </head>

    <body>
       
        {% include "header.html" %}
        
        {% block content %}{% endblock %}
        
        {% include "footer.html" %}
        
        {% include "nav_bottom.html" %}
        
    </body>
    
<script src="/static/asset/jquery-2.1.3.js"></script>
<script src="/static/asset/bootstrap/jquery-3.2.1.js"></script>
<script src="/static/asset/bootstrap/js/bootstrap.js"></script>
<script src="/static/asset/bootstrap/js/bootstrap.bundle.js"></script>
<script src="/static/asset/custom.js"></script>
<script src="/static/asset/slide/js/lightslider.js"></script>

{% block js %}{% endblock %}
</html>

templates/daftar.html
{% extends "base.html" %}

{% block css %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/asset/style.css" type="text/css">
    <link rel="stylesheet" href="/static/asset/slide/css/lightslider.css" />
    <link rel="stylesheet" href="/static/asset/css/home.css">
    <link rel="stylesheet" href="/static/asset/index.css">
    <link rel="stylesheet" href="/static/asset/css/transaksi.css">
    <link rel="stylesheet" href="/static/asset/responsive.css" type="text/css"> 
{% endblock %}
  
{% block content %}
   <center>
    <div class="container">
        <div class="col-xl-4" style="padding-top: 110px;">
            <form id="register" method="POST">
                {% csrf_token %}
                <p class="h2 text-right">Daftar</p>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">
                            <i class="fa fa-user-o" aria-hidden="true"></i>
                        </span>
                    </div>
                    <input type="text" class="form-control" placeholder="Nama Lengkap" aria-label="Nama Lengkap" aria-describedby="basic-addon1" required name="nama" id="nama" autofocus>
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">@
                        </span>
                    </div>
                    <input type="email" class="form-control" placeholder="Email" aria-label="Email" aria-describedby="basic-addon1" required name="email" id="email">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">
                            <i class="fa fa-phone-square" aria-hidden="true"></i>
                        </span>
                    </div>
                    <input type="text" class="form-control" placeholder="No Hanphone Contoh +628123456***" aria-label="No Hanphone Contoh +628123456789" aria-describedby="basic-addon1" required name="phone" name="id">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fa fa-lock" aria-hidden="true"></i></span>
                    </div>
                    <input type="text" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1" name="pass"  id="pass" required min="8">
                </div>
                <div class="form-check" style="text-align: left;">
                    <label class="form-check-label txt_lbl" for="exampleCheck1">Mendaftar Berarti Setuju Dengan </label><a href="#" class="txt_lbl_a"> Syarat & Ketentuan</a>
                </div>
                <br>
                <input type="hidden" name="akses" value="daftar">
                <button type="submit" class="btn btn-success" style="width: 100%;" name="btn_reg">Daftar Sekarang</button>
                
            </form>
        </div>
    </div>
</center>
{% endblock %}
{% block js %}
<script type="text/javascript" src="/static/asset/js/jquery.form.min.js"></script>
<script>
    
   $(document).ready(function() {
       var options = {
           beforeSubmit: function() {
               $('button[name=btn_reg]').html('Loading...');
               $('button[name=btn_reg]').prop('disabled', true);
           },
           success: showResponse,
           url: "{% url 'daftaruser' %}",
       };

       $('#register').submit(function() {
           $(this).ajaxSubmit(options);
           return false;
       });
    });
    function btnDsbl(){
        $('button[name=btn_reg]').html('Register');
        $('button[name=btn_reg]').prop('disabled', false);
    }

   function showResponse(responseText, statusText, xhr, $form) {
       if (responseText == 'successregister') {
         $('button[name=btn_reg]').html('Done');
         $('button[name=btn_reg]').prop('disabled', true);
         alert("Anda berhasil register")
         window.location.href = "/profile";
       } else if (responseText == "emailtaken") {
         $('#status-reg').html('Email Taken');
       } else {
           btnDsbl()
           $('#status-reg').html('Gagal register');
       } 
       
   }

</script>
{% endblock %}

templates/footer.html
<div class="footer_countainer">
    <center>
        <div class="top_poster">
        </div>
        <div class="poster">
            <p class="perlu">Butuh bantuan untuk investasimu ? </p>
            <a class="btn btn-success btn-lg" href="https://api.whatsapp.com/send?phone=6283122412167&text=Halo%20Saya%20Ingin%20Menginfokan%20Investasi" role="button" target="_blank" class="chat_btm">Kirm Pesan <i class="fa fa-whatsapp " aria-hidden="true"> </i> </a>
        </div>
    </center>


    <span class="munggah"><i class="fa fa-chevron-up" aria-hidden="true"></i></span>
</div>

templates/header.html
<div class="custom_nav_logo_atas">

{% if request.user_agent.is_mobile %}
   
    {% if not profile %}
           
        <a href="/">
            <img src="/static/asset/icon/logo_circle.png"alt="" class="logo_custom1">
        </a> 
            
    {% endif %}
    
{% else %}
   
    <nav class="nav_custom_top navbar navbar-expand-lg navbar-light fixed-top ">
            <a class="navbar-brand" href="/">
                <img src="/static/asset/icon/logo.png"alt="" class="logo_custom">
            </a> 
    {% if request.user.is_authenticated %}
       
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto"></ul>
            <div class="nav-item" style="margin-right: 100px;">
                <a href="/profile">
                    <div class="btn-group">
                        <li class="nav-item dropdown" style="list-style: none;">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                             
                                    {% load main_tags %}
                              <div class="pp_t_header">
                                    {{ request.user.id|getname|make_list|first|upper }}
                              </div>
                              
                                <span class="name_circle">
                                    {{ request.user.id|getname}}</span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="/profile">Dashboard</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="/logout">Log Out</a>
                            </div>
                        </li>
                    </div>
                </a>
            </div>
        </div>

    {% else %}

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto"></ul>
            <div class="nav-item" style="margin-right: 20px;">
                <a href="/daftar">
                        <button type="button" class="btn btn-light" style="padding: 5px 20px 5px 20px" ><i class="fa fa-user-o"> </i> Daftar</button>
                    </a>
            </div>
            <br>
            <div class="nav-item" style="margin-right: 100px;">
                <a href="/login">
                        <button type="button" class="btn btn-success" style="padding: 5px 20px 5px 20px">Masuk</button>
                    </a>
            </div>
        </div>


    {% endif %}
    </nav>
{%endif%}
</div>

templates/home.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/asset/style.css" type="text/css">
    <link rel="stylesheet" href="/static/asset/slide/css/lightslider.css" />
    <link rel="stylesheet" href="/static/asset/css/home.css">
    <link rel="stylesheet" href="/static/asset/css/transaksi.css">
    <link rel="stylesheet" href="/static/asset/responsive.css" type="text/css"> 
{% endblock %}

 
{% block content %}
{% load humanize %} 
    <div class="header_home" id="atas">
       <div class="overlay">
        <div class="col-sm-12">
            <center>
                <h2 class="title_home">Platform Investasi Pertanian Organik #1
                </h2>
                <p class="title2">Berinvestasi sambil membantu pertanian banyuwangi</p>
                <p class="lead lead1">
                    <a class="putih btn btn-warning2 btn-lg " href="/#mengapa" role="button">Mengapa PIPO ?</a>
                </p>
                <p class="lead lead1">
                    <a class="btn btn-success btn-lg " href="/#inves" role="button">Cara Investasi</a>
                </p>
            </center>
        </div>
        </div>
    </div>
    <center>
        <div id="mengapa"></div>
        <div class="scrool_beh">
            <div class="container pdgtop50">
                <div class="row">
                    <div class="col-sm-12 mrgnbtn50">
                        <h2 class="mengapa_p">Mengapa Pipo Untuk Investasi Anda ?</h2>
                        <div class="heading-orange-divider" style="margin-top: 20px; margin-bottom: 12px;"></div>
                    </div>
                </div>
                <div class="row justify-content-md-center">
                    <div class="col-sm-3 box_white">
                        <img src="static/asset/icon/about-plamber-2.jpg" alt="" class="img_desk">
                    </div>
                    <div class="col-sm-3 box_black">
                        <h4>
                            <b>Investasi Menguntungkan</b>
                        </h4>
                        <p class="desk_box">
                            Anda akan mendapat bagi hasil dari investasi yang anda lakukan
                        </p>
                    </div>
                    <div class="col-sm-3 box_white">
                        <img src="static/asset/icon/project5.jpg" alt="" class="img_desk">
                    </div>
                    <div class="col-sm-3 box_black">
                        <h4>
                            <b>Membantu Pertanian Organik</b>
                        </h4>
                        <p class="desk_box">
                            Investasi anda membantu petani untuk menggunakan methode bertani Organik
                        </p>
                    </div>
                    <div class="col-sm-3 box_black order2">
                        <h4>
                            <b>Memperbaiki Tanah</b>
                        </h4>
                        <p class="desk_box ">
                            Dari pertanian organik, anda secara tidak langsung membantu pemulihan tanah pertanian yang sudah rusak karena bahan kimia
                        </p>
                    </div>
                    <div class="col-sm-3 box_white order1">
                        <img src="static/asset/icon/project4.jpg" alt="" class="img_desk">
                    </div>
                    <div class="col-sm-3 box_black order4">
                        <h4>
                            <b>Kontribusi Pangan Sehat</b>
                        </h4>
                        <p class="desk_box">
                            Dari investasi anda, anda sudah berkontribusi untuk menciptakan pangan sehat dari hasil investasi pertanian organik
                        </p>
                    </div>
                    <div class="col-sm-3 box_white order3">
                        <img src="static/asset/icon/project2.jpg" alt="" class="img_desk">
                    </div>
                </div>
            </div>
        </div>

        <div id="inves"></div>
        <div style="" class="scrool_beh_btm">
            <div class="container c-inves">
                <br>
                <center>
                    <div class="row">
                        <div class="col-12">
                        <h2 class="mengapa_p">Lima Langkah Untuk Memulai Investasimu</h2>
                        <div class="heading-green-divider" style="margin-top: 20px; margin-bottom: 12px;">
                        </div>
                        </div>
                        <br>
                        <br>
                        <br>
                        <div class="col-sm footer_desk">
                            <img src="/static/asset/icon/plant%20(1).svg" alt="investasi pertanian" class="w100px">
                            <p class="title_why">1. Pilih Proyekmu</p>
                            <p class="isi_why">Pilih jenis proyek investasi berdasarkan waktu, risiko, dan keuntungan yang Kamu inginkan</p>
                        </div>
                        <div class="col-sm footer_desk">
                            <img src="/static/asset/icon/farmer%20(1).svg" alt="investasi pertanian" class="w100px">
                            <p class="title_why">2. Daftar Atau Login</p>
                            <p class="isi_why">Klik tombol Daftar yang ada di pojok kanan atas halaman ini untuk langsung bergabung!</p>
                        </div>
                        <div class="col-sm footer_desk">
                            <img src="/static/asset/icon/growth.svg" alt="investasi pertanian" class="w100px">
                            <p class="title_why">3. Mulai Investasi</p>
                            <p class="isi_why">Transfer uang investasi sesuai jumlah yang kamu ingin investasikan</p>
                        </div>
                        <div class="col-sm footer_desk">
                            <img src="/static/asset/icon/plant%20(2).svg" alt="" class="w100px">
                            <p class="title_why">4. Pantau Investasimu</p>
                            <p class="isi_why">Pantau perkembangan investasi proyekmu melalui user dashboard mu disini
                            </p>
                        </div>
                        <div class="col-sm footer_desk">
                            <img src="/static/asset/icon/harvest.svg" alt="" class="w100px">
                            <p class="title_why">5. Dapatkan Panenmu</p>
                            <p class="isi_why">Dapatkan uang investasimu beserta keuntungan panenmu </p>
                        </div>
                    </div>
                </center>
            </div>
        </div>
        <div class="container">
            <div class="row">
            <div id="proyek"></div>
        <div class="col-sm-12">
           <div class="memilih-ico"></div>
        </div>
        <div class="container c-proyek">
            <div class="row">
                {% for i in objects %}
                <div class="col">
                    <a href="{% url 'detailproject' i.slug %}" class="nonetxt" style="text-decoration: none;">
                        <div class="card hover-card">

                            <!-- optimasi 1  -->
                            <img class="card-img-top" src="{{i.photo.url}}" alt="Card image cap">
                            <div class="card-body">
                                <h6 class="card-title2 text-left title-card bold"><b>{{i.name}}</b></h6>

                                <table class="table-md tb-proyek" border="0">
                                    <tr>
                                        <td>Kebutuhan Dana</td>
                                        <td>:</td>
                                        <td>Rp. {{i.finding_needs|intcomma }}</td>
                                    </tr>
                                    <tr>
                                        <td>Lama Investasi</td>
                                        <td>:</td>
                                        <td>{{i.lama_investasi }} Hari</td>
                                    </tr>
                                    <tr>
                                        <td>Resiko</td>
                                        <td>:</td>
                                        <td>{{i.get_risk_status_display}}</td>
                                    </tr>
                                    <tr>
                                        <td>Lokasi</td>
                                        <td>:</td>
                                        <td>{{i.lokasi}}</td>
                                    </tr>
                                </table>
                                
                                <div class="progress progress_custom">
                                    <div class="progress-bar-animated progress-bar-striped progress-bar bg-success" role="progressbar" aria-valuenow="{{i.get_persen}}" aria-valuemin="0" aria-valuemax="100" style="width: {{i.get_persen}}%">
                                    {{i.get_persen}}%</div>
                                </div>


                            </div>
                            <div class="bg-sil float_left">
                                <table class="table-sm tb-des" border="0">
                                    <tr>
                                        <td>Dana Terkumpul</td>
                                        <td>:</td>
                                        <td>{{i.get_pendanaan|intcomma}}</td>
                                    </tr>
                                </table>

                                <button type="button" class="btn btn-warning btn-lg btn-block"><strong>Lihat Investasi</strong></button>

                            </div>

                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>

            <button type="button" class="btn btn-success btn-lg btn-block">Lihat Semua Proyek</button>

        </div>
        
        
        
        </div>
        </div>
        
        <!--
        <div class="pilih_in">
            <div class="container">
                <div class="row justify-content-md-center">
                    <div class="col-12">
                        <img src="/static/asset/icon/plane.svg" alt="" style="" class="img_plane mgbtm150px">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 pilih_p1">
                        <a href="#/pertanian/#atas">
                            <div class="gambar_sawah">
                                <img src="/static/asset/icon/pertanian.svg" alt="">
                            </div>
                        </a>
                    </div>
                    <div class="col-sm-6 pilih_p">
                        <a href="#/peternakan/#atas">
                            <div class="gambar_sapi">
                                <img src="/static/asset/icon/peternakan.svg" alt="" class="img_s">
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        
        -->
    </center>
    
{% endblock %} 

templates/login.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/asset/style.css" type="text/css">
    <link rel="stylesheet" href="/static/asset/slide/css/lightslider.css" />
    <link rel="stylesheet" href="/static/asset/css/home.css">
    <link rel="stylesheet" href="/static/asset/index.css">
    <link rel="stylesheet" href="/static/asset/css/transaksi.css">
    <link rel="stylesheet" href="/static/asset/responsive.css" type="text/css"> 
{% endblock %}

{% block content %}
   <center>
    <div class="container">
       
        <div class="col-xl-4" style="padding-top: 110px;">
                {% csrf_token %}
                <p class="h2 text-right">Masuk</p>
                <div class="form-group">
                    <input type="email" class="form-control" id="username" aria-describedby="emailHelp" placeholder="Masukan Alamat Email" name="username" required autofocus>
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" id="password" placeholder="Masukan Kata Sandi" name="password" required>
                </div>
                <button type="button" class="btn btn-success" style="width: 100%;" name="login" id="login">Masuk</button>



                <small id="emailHelp" class="form-text text-muted">Tidak Memiliki Akun  ?</small>
                <a href="/daftar">
                    <div class="btn btn-info" style="width: 100%;">Daftar</div>
                </a>
                
                <div id="status-login"></div>
        </div>
    </div>
</center>
{% endblock %}


{% block js %}
<script>
  $("#login").on("click", function() {
    if ($('#username').val()!='' && $('#password').val()!='') {
       $.ajax({
           type:"POST",
           cache:false,
           url: "{% url 'login' %}",
           data: {'username': $('#username').val(),
            'password': $('#password').val(),
            'csrfmiddlewaretoken': '{{ csrf_token }}',
           },
           beforeSend:function(){
              $('#status-login').html('<p>loading</p>');
           },
           success:function(resp){
             $('#status-login').text('')
              if ( resp === "inactive") {
              $('#status-login').text("user belum aktif")
             } else if ( resp === "failed_login") {
               $('#status-login').text('gagal login. periksa user dan password');
             } else {
                  window.location = "/profile";
             }
           }
        });
  } else {
     $('#status-login').html("tolong input username dan password");
  }

});
</script>
{% endblock %}